"""add dispensing_records

Revision ID: 2249dfc54fae
Revises: 
Create Date: 2026-03-22 06:51:37.047689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2249dfc54fae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('dispensing_records',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('dispensed_at', sa.Date(), nullable=False, comment='Date the medicine was dispensed'),
    # sa.Column('facility_name', sa.String(length=500), nullable=False),
    # sa.Column('hasc_id', sa.String(length=20), nullable=True, comment='District HASC code e.g. BW.GB'),
    # sa.Column('nappi_code', sa.String(length=50), nullable=True),
    # sa.Column('product_name', sa.String(length=500), nullable=False),
    # sa.Column('atc_code', sa.String(length=20), nullable=True, comment='WHO ATC code — links medicine to disease category'),
    # sa.Column('atc_description', sa.String(length=200), nullable=True),
    # sa.Column('quantity', sa.Integer(), nullable=False),
    # sa.Column('icd_code', sa.String(length=20), nullable=True, comment='ICD-10 code linked to this dispensing event'),
    # sa.Column('icd_description', sa.String(length=300), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_dispensing_records_atc_code'), 'dispensing_records', ['atc_code'], unique=False)
    # op.create_index(op.f('ix_dispensing_records_dispensed_at'), 'dispensing_records', ['dispensed_at'], unique=False)
    # op.create_index(op.f('ix_dispensing_records_facility_name'), 'dispensing_records', ['facility_name'], unique=False)
    # op.create_index(op.f('ix_dispensing_records_hasc_id'), 'dispensing_records', ['hasc_id'], unique=False)
    # op.create_index(op.f('ix_dispensing_records_icd_code'), 'dispensing_records', ['icd_code'], unique=False)
    # op.create_index(op.f('ix_dispensing_records_nappi_code'), 'dispensing_records', ['nappi_code'], unique=False)
    # op.create_table('districts',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('hasc_id', sa.String(length=20), nullable=False, comment='e.g. BW.GB'),
    # sa.Column('district_name', sa.String(length=100), nullable=False),
    # sa.Column('centroid_lat', sa.Float(), nullable=True),
    # sa.Column('centroid_lon', sa.Float(), nullable=True),
    # sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='GeoJSON MultiPolygon coordinates array'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_districts_hasc_id'), 'districts', ['hasc_id'], unique=True)
    # op.create_table('facilities',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('facility_name', sa.String(length=500), nullable=False),
    # sa.Column('facility_type', sa.String(length=100), nullable=True, comment='Hospital | Clinic | Health Post | Pharmacy | Dental Clinic | etc.'),
    # sa.Column('latitude', sa.Float(), nullable=True),
    # sa.Column('longitude', sa.Float(), nullable=True),
    # sa.Column('has_coordinates', sa.Boolean(), nullable=False),
    # sa.Column('hasc_id', sa.String(length=20), nullable=True, comment='e.g. BW.GB — assigned via nearest district centroid'),
    # sa.Column('district_name', sa.String(length=100), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_facilities_facility_name'), 'facilities', ['facility_name'], unique=True)
    # op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    # op.create_index(op.f('ix_facilities_has_coordinates'), 'facilities', ['has_coordinates'], unique=False)
    # op.create_index(op.f('ix_facilities_hasc_id'), 'facilities', ['hasc_id'], unique=False)
    # op.create_table('icd10_codes',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('order_number', sa.Integer(), nullable=True),
    # sa.Column('code', sa.String(length=20), nullable=False),
    # sa.Column('is_valid', sa.Boolean(), nullable=False, comment='True = billable/leaf code'),
    # sa.Column('short_description', sa.String(length=500), nullable=True),
    # sa.Column('long_description', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_icd10_codes_code'), 'icd10_codes', ['code'], unique=True)
    # op.create_index(op.f('ix_icd10_codes_is_valid'), 'icd10_codes', ['is_valid'], unique=False)
    # op.create_table('medicines',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('nappi_code', sa.String(length=50), nullable=True),
    # sa.Column('product_name', sa.String(length=500), nullable=False),
    # sa.Column('dosage_form', sa.String(length=20), nullable=True),
    # sa.Column('schedule', sa.String(length=50), nullable=True),
    # sa.Column('nappi_status', sa.String(length=50), nullable=True, comment='Active | Discontinued'),
    # sa.Column('supplier_name', sa.String(length=300), nullable=True),
    # sa.Column('who_atc_code', sa.String(length=20), nullable=True),
    # sa.Column('who_atc_description', sa.String(length=300), nullable=True),
    # sa.Column('active_on_primary_healthcare_eml', sa.String(length=10), nullable=True),
    # sa.Column('active_on_adult_hospital_eml', sa.String(length=10), nullable=True),
    # sa.Column('active_on_paediatric_hospital_eml', sa.String(length=10), nullable=True),
    # sa.Column('active_on_tertiary_quaternary_eml', sa.String(length=10), nullable=True),
    # sa.Column('active_on_master_procurement_catalogue', sa.String(length=10), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # # )
    # op.create_index(op.f('ix_medicines_nappi_code'), 'medicines', ['nappi_code'], unique=True)
    # op.create_index(op.f('ix_medicines_nappi_status'), 'medicines', ['nappi_status'], unique=False)
    # op.create_index(op.f('ix_medicines_product_name'), 'medicines', ['product_name'], unique=False)
    # op.create_index(op.f('ix_medicines_who_atc_code'), 'medicines', ['who_atc_code'], unique=False)
    op.create_table('search_clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_event_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('result_label', sa.String(length=500), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('result_subtype', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_clicks_created_at'), 'search_clicks', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_clicks_result_type'), 'search_clicks', ['result_type'], unique=False)
    op.create_index(op.f('ix_search_clicks_search_event_id'), 'search_clicks', ['search_event_id'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='facility | medicine | disease | all'),
    sa.Column('results_returned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_events_created_at'), 'search_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_events_entity_type'), 'search_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_search_events_query'), 'search_events', ['query'], unique=False)
    op.create_table('surveillance_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='search_spike | dispensing_spike'),
    sa.Column('signal', sa.String(length=500), nullable=False, comment='The ICD code, disease name, or medicine that triggered the alert'),
    sa.Column('hasc_id', sa.String(length=20), nullable=True),
    sa.Column('district_name', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('observed_count', sa.Integer(), nullable=False, comment='Actual count in the alert period'),
    sa.Column('baseline_count', sa.Float(), nullable=False, comment='Rolling average baseline count'),
    sa.Column('z_score', sa.Float(), nullable=False, comment='Standard deviations above baseline'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='low | medium | high — based on z_score thresholds'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='False once alert is resolved/acknowledged'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveillance_alerts_alert_type'), 'surveillance_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_surveillance_alerts_created_at'), 'surveillance_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_surveillance_alerts_hasc_id'), 'surveillance_alerts', ['hasc_id'], unique=False)
    op.create_index(op.f('ix_surveillance_alerts_severity'), 'surveillance_alerts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('botswana_health_centers',
    # sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    # sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True)
    # )
    # op.create_table('idc_10_disease_classification',
    # sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('atc_code', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True)
    # )
    # op.create_table('product_sources_detailed',
    # sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('record_type_identifier', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('parent_company_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('product_source_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('product_source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('product_source_indicator', sa.CHAR(length=1), autoincrement=False, nullable=True),
    # sa.Column('filler', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('record_update_date', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('record_update_time', postgresql.TIME(), autoincrement=False, nullable=True)
    # )
    # op.create_table('botswana_district_boundaries',
    # sa.Column('hasc_id', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('geometry_type', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('polygon_idx', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('ring_idx', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('point_idx', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    # sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True)
    # )
    # op.create_table('product_sources',
    # sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('record_type_identifier', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('nappi_product_code', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('nappi_suffix', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('product_strength', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('dosage_form_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('product_pack_size', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('manufacturer_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('ean_product_code', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('catalogue_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('product_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('number_of_uses', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('filler', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('full_product_name', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('record_update_date', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('record_update_time', postgresql.TIME(), autoincrement=False, nullable=True)
    # )
    # op.create_table('atc',
    # sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True)
    # )
    op.drop_index(op.f('ix_surveillance_alerts_severity'), table_name='surveillance_alerts')
    op.drop_index(op.f('ix_surveillance_alerts_hasc_id'), table_name='surveillance_alerts')
    op.drop_index(op.f('ix_surveillance_alerts_created_at'), table_name='surveillance_alerts')
    op.drop_index(op.f('ix_surveillance_alerts_alert_type'), table_name='surveillance_alerts')
    op.drop_table('surveillance_alerts')
    op.drop_index(op.f('ix_search_events_query'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_entity_type'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_created_at'), table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_search_clicks_search_event_id'), table_name='search_clicks')
    op.drop_index(op.f('ix_search_clicks_result_type'), table_name='search_clicks')
    op.drop_index(op.f('ix_search_clicks_created_at'), table_name='search_clicks')
    op.drop_table('search_clicks')
    # op.drop_index(op.f('ix_medicines_who_atc_code'), table_name='medicines')
    # op.drop_index(op.f('ix_medicines_product_name'), table_name='medicines')
    # op.drop_index(op.f('ix_medicines_nappi_status'), table_name='medicines')
    # op.drop_index(op.f('ix_medicines_nappi_code'), table_name='medicines')
    # op.drop_table('medicines')
    # op.drop_index(op.f('ix_icd10_codes_is_valid'), table_name='icd10_codes')
    # op.drop_index(op.f('ix_icd10_codes_code'), table_name='icd10_codes')
    # op.drop_table('icd10_codes')
    # op.drop_index(op.f('ix_facilities_hasc_id'), table_name='facilities')
    # op.drop_index(op.f('ix_facilities_has_coordinates'), table_name='facilities')
    # op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    # op.drop_index(op.f('ix_facilities_facility_name'), table_name='facilities')
    # op.drop_table('facilities')
    # op.drop_index(op.f('ix_districts_hasc_id'), table_name='districts')
    # op.drop_table('districts')
    # op.drop_index(op.f('ix_dispensing_records_nappi_code'), table_name='dispensing_records')
    # op.drop_index(op.f('ix_dispensing_records_icd_code'), table_name='dispensing_records')
    # op.drop_index(op.f('ix_dispensing_records_hasc_id'), table_name='dispensing_records')
    # op.drop_index(op.f('ix_dispensing_records_facility_name'), table_name='dispensing_records')
    # op.drop_index(op.f('ix_dispensing_records_dispensed_at'), table_name='dispensing_records')
    # op.drop_index(op.f('ix_dispensing_records_atc_code'), table_name='dispensing_records')
    # op.drop_table('dispensing_records')
    # ### end Alembic commands ###
